# Generated by Django 3.1.4 on 2020-12-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
